### PR TITLE
Fixed ErrorBoundary

### LINKED ISSUE #104: Error Boundary is not catching errors
**Describe the bug**

Error Boundary is not catching errors 

**To Reproduce**

**Expected behavior**

Error boundary must send an error to DB and redirect to error page

### PR DESCRIPTION
**Pull request by e-azocar**
### Description

The initial problem with the Error Boundary was that, it didn't catch the errors.
In the React documentation, they explain the errors that this component can't catch

Currently the `ErrorBoundary` can catch errors like `throw new Error("error message")`, `[].toUpperCase()`, `undefined.data`. However, the errors of compilation, errors of asyncronous code or Javascript syntax errors, can't be catched for this.

fixes #104 

#### Screenshots
image

### CODE REVIEW

File: src/layouts/ErrorBoundary.js [hunk 1]
```diff
@@ -6,32 +6,23 @@ import { logError } from '../helpers'
...
-    }
+    this.state = { error: null, errorInfo: null }
   }
 
   componentDidCatch(error, errorInfo) {
-    this.setState({ errorInfo, error })
+    this.setState({
+      error: error,
+      errorInfo: errorInfo,
+    })
```
Comment (heliomar-pena) [inline src/layouts/ErrorBoundary.js:14]: I'm confused because i don't find that setState method was declared. At this case don't should u to use `this.state` directly?

**Review by heliomar-pena — COMMENTED** [review]
A little question

File: src/layouts/ErrorBoundary.js (hunk 1 above)
Comment (heliomar-pena) [reply src/layouts/ErrorBoundary.js:14]: setState method is inherited from parent at the line 8?

Comment (heliomar-pena) [reply src/layouts/ErrorBoundary.js:14]: I checked and is good. This is the documentation that I check:

https://es.reactjs.org/docs/composition-vs-inheritance.html

**Comment by Israel-Laguan** [comment]
can you explain which error does this catch?

Maybe make a list or describe step by step

**Comment by e-azocar** [comment]
> can you explain which error does this catch?
> 
> Maybe make a list or describe step by step

I added a short list of errors that `ErrorBoundary` can catch

**Review by Israel-Laguan — APPROVED** [review]

**Review by heliomar-pena — APPROVED** [review]
Looks good! thanks

File: src/layouts/ErrorBoundary.js [hunk 2]
```diff
@@ -1,37 +1,44 @@
 import { Component } from 'react'
 import PropTypes from 'prop-types'
-import Error from '../pages/Error'
-import { logError } from '../helpers'
+// import { logError } from '../helpers'
```
Comment (heliomar-pena) [inline src/layouts/ErrorBoundary.js]: Please remove comment

**Review by heliomar-pena — COMMENTED** [review]
Please remove the comment and we could merge

File: src/layouts/ErrorBoundary.js (hunk 2 above)
Comment (e-azocar) [reply src/layouts/ErrorBoundary.js]: It's done

**Review by heliomar-pena — APPROVED** [review]
